version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_tracking
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    container_name: "times-backend"
    image: ghcr.io/valcriss/personnal-time-tracking-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/time_tracking
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    image: ghcr.io/valcriss/personnal-time-tracking-frontend:latest
    container_name: "times-frontend"
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  db_data:
